# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/will/Projects/tuntap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/will/Projects/tuntap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Projects/tuntap/CMakeFiles /home/will/Projects/tuntap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Projects/tuntap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SoftNetworkAdapter

# Build rule for target.
SoftNetworkAdapter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SoftNetworkAdapter
.PHONY : SoftNetworkAdapter

# fast build rule for target.
SoftNetworkAdapter/fast:
	$(MAKE) -f CMakeFiles/SoftNetworkAdapter.dir/build.make CMakeFiles/SoftNetworkAdapter.dir/build
.PHONY : SoftNetworkAdapter/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named networkadapter

# Build rule for target.
networkadapter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 networkadapter
.PHONY : networkadapter

# fast build rule for target.
networkadapter/fast:
	$(MAKE) -f networkadapter/CMakeFiles/networkadapter.dir/build.make networkadapter/CMakeFiles/networkadapter.dir/build
.PHONY : networkadapter/fast

#=============================================================================
# Target rules for targets named networkstack

# Build rule for target.
networkstack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 networkstack
.PHONY : networkstack

# fast build rule for target.
networkstack/fast:
	$(MAKE) -f networkstack/CMakeFiles/networkstack.dir/build.make networkstack/CMakeFiles/networkstack.dir/build
.PHONY : networkstack/fast

#=============================================================================
# Target rules for targets named networkutils

# Build rule for target.
networkutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 networkutils
.PHONY : networkutils

# fast build rule for target.
networkutils/fast:
	$(MAKE) -f networkutils/CMakeFiles/networkutils.dir/build.make networkutils/CMakeFiles/networkutils.dir/build
.PHONY : networkutils/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SoftNetworkAdapter.dir/build.make CMakeFiles/SoftNetworkAdapter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SoftNetworkAdapter.dir/build.make CMakeFiles/SoftNetworkAdapter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SoftNetworkAdapter.dir/build.make CMakeFiles/SoftNetworkAdapter.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SoftNetworkAdapter"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... networkadapter"
	@echo "... networkstack"
	@echo "... networkutils"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

